### ISSUE TITLE
3.2 X axis label change

### ISSUE THREAD

**Issue by RebeccaJLai** [debruine/shiny-tutorials#4]
![solution code 1](https://user-images.githubusercontent.com/33028772/44557351-ee6c9980-a735-11e8-9a80-eb765a100f69.JPG)

Solution code given to change x axis label doesn't change the x axis label. Does it need to be this instead?

![solution code 2](https://user-images.githubusercontent.com/33028772/44557365-06441d80-a736-11e8-958a-0eb4d3a0f375.JPG)

**Comment by debruine** [comment]
Thanks, fixed!
